package:
    name: pyramses
    version: '0.0.22'
source:
    path: ../src

build:
    noarch: generic

requirements:
    build:
        - python
        - numpy
        - scipy
        - matplotlib
        - mkl
        - intel-openmp
        - Setuptools
    run:
        - python
        - mkl
        - numpy
        - scipy
        - matplotlib
        - intel-openmp

about:
    home: https://pyramses.sps-lab.org
    license: Other/Proprietary License
    license_file: LICENSE.rst
    summary: Python library for RAMSES dynamic simulator.
